source 'http://rubygems.org'

gem 'activesupport', '~> 5.0'
gem 'activerecord', '~> 5.0'
gem 'rake', '~> 10.4'
gem 'pg', '~> 0.10'
gem 'sinatra', '~> 1.4'
gem 'sinatra-flash', '~> 0.3.0'
gem 'sinatra-partial', '~> 1.0'
gem 'sinatra-static-assets', '~> 1.0'
gem 'slim', '~> 3.0'
gem 'json', '~> 1.8'
gem 'pg_query', '~> 0.11.2'
gem 'rack', '~> 1.6'
gem 'shotgun', '~> 0.9.1'
gem 'anbt-sql-formatter', '~> 0.0.5'
