source 'http://rubygems.org'

gem 'activesupport', '~> 5.0'
gem 'activerecord', '~> 5.0'
gem 'rake', '~> 12.0.0'
gem 'pg', '~> 0.19.0'
gem 'sinatra', '~> 1.4'
gem 'sinatra-flash', '~> 0.3.0'
gem 'sinatra-partial', '~> 1.0'
gem 'sinatra-static-assets', '~> 1.0'
gem 'slim', '~> 3.0'
gem 'json', '~> 2.0.2'
gem 'pg_query', '~> 0.11.3'
gem 'rack', '~> 2.0.1'
gem 'shotgun', '~> 0.9.2'
gem 'anbt-sql-formatter', '~> 0.0.5'
