source 'http://rubygems.org'

gem 'activerecord', '~> 5.0'
gem 'pg', '~> 0.19.0'
gem 'sinatra', '~> 1.4'
gem 'sinatra-static-assets', '~> 1.0'
gem 'slim', '~> 3.0'
gem 'json', '~> 1.8'
gem 'pg_query', '~> 0.11.3'
gem 'anbt-sql-formatter', '~> 0.0.5'
gem 'rack', '~> 1.6'
gem 'shotgun', '~> 0.9.2'
